urls = ['https://api.spacexdata.com/v4/capsules',
        'https://api.spacexdata.com/v4/company',
        'https://api.spacexdata.com/v4/cores',
        'https://api.spacexdata.com/v4/crew',
        'https://api.spacexdata.com/v4/dragons',
        'https://api.spacexdata.com/v4/landpads',
        'https://api.spacexdata.com/v4/launches',
        'https://api.spacexdata.com/v4/launches/past',
        'https://api.spacexdata.com/v4/launches/upcoming',
        'https://api.spacexdata.com/v4/launches/latest',
        'https://api.spacexdata.com/v4/launches/next',
        'https://api.spacexdata.com/v4/launchpads',
        'https://api.spacexdata.com/v4/payloads',
        'https://api.spacexdata.com/v4/roadster',
        'https://api.spacexdata.com/v4/rockets',
        'https://api.spacexdata.com/v4/ships',
        'https://api.spacexdata.com/v4/starlink']